#!/bin/bash

git config --global pull.rebase false
git config --global user.name "your-username"
git config --global user.email "your-email@gmail.com"
git config --global credential.helper cache
git config --global credential.helper 'cache --timeout=31536000'

--------------------

Quick setup — if you’ve done this kind of thing before
or

Get started by creating a new file or uploading an existing file. We recommend every repository include a README, LICENSE, and .gitignore.
…or create a new repository on the command line

echo "# git-setup-01" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/anasir514/git-setup-01.git
git push -u origin main

…or push an existing repository from the command line

git remote add origin https://github.com/anasir514/git-setup-01.git
git branch -M main
git push -u origin main
